export default [
    {
        type:1,
        content:[
            {
                index:1,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'php',
                    },{
                    answerindex:2,
                    answertitle:'c/c++',
                    },{
                    answerindex:3,
                    answertitle:'java',
                    },{
                    answerindex:4,
                    answertitle:'js',
                    }],
                    title:'以下哪个语言是世界上最好的语言'
                },
                rightanswer:4
            },
            {
                index:2,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'谁敢说小编的坏话？我保证不打屎他',
                    },{
                    answerindex:2,
                    answertitle:'小编是大牛',
                    },{
                    answerindex:3,
                    answertitle:'小编你最棒',
                    },{
                    answerindex:4,
                    answertitle:'小编瞎扯？不存在的',
                    }],
                    title:'我仿佛听到谁在说小编的坏话'
                },
                rightanswer:4
            },
            {
                index:3,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'小编',
                    },{
                    answerindex:2,
                    answertitle:'你',
                    },{
                    answerindex:3,
                    answertitle:'我',
                    },{
                    answerindex:4,
                    answertitle:'还用考虑？肯定是小编啦',
                    }],
                    title:'谁是你最喜欢的人'
                },
                rightanswer:4
            },
        ]
    },
    {
        type:2,
        content:[
            {
                index:1,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'小编',
                    },{
                    answerindex:2,
                    answertitle:'你',
                    },{
                    answerindex:3,
                    answertitle:'我',
                    },{
                    answerindex:4,
                    answertitle:'还用考虑？肯定是小编啦',
                    }],
                    title:'谁是最帅的人？'
                },
                rightanswer:4
            },
            {
                index:2,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'小编',
                    },{
                    answerindex:2,
                    answertitle:'你',
                    },{
                    answerindex:3,
                    answertitle:'我',
                    },{
                    answerindex:4,
                    answertitle:'还用考虑？肯定是小编啦',
                    }],
                    title:'谁是智多星'
                },
                rightanswer:4
            },
            {
                index:3,
                question:
                    {
                        answer:[{
                    answerindex:1,
                    answertitle:'小编',
                    },{
                    answerindex:2,
                    answertitle:'你',
                    },{
                    answerindex:3,
                    answertitle:'我',
                    },{
                    answerindex:4,
                    answertitle:'还用考虑？肯定是小编啦',
                    }],
                    title:'谁是你最喜欢的人'
                },
                rightanswer:4
            },
        ]
    },
]